<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class PatnaSchoolsSeeder extends Seeder
{
    public function run(): void
    {
        // ── Ensure Roles Exist ──────────────────────────────────────────
        $adminRole  = Role::firstOrCreate(['name' => 'admin']);
        $ownerRole  = Role::firstOrCreate(['name' => 'school_owner']);
        $parentRole = Role::firstOrCreate(['name' => 'parent']);

        // ── Clean & Fresh Test Logins ───────────────────────────────────
        $adminUser = User::updateOrCreate(
            ['email' => 'admin@schoolmapr.com'],
            [
                'name'     => 'SchoolMapr Admin',
                'password' => Hash::make('admin123'),
                'phone'    => '+91 9876543210',
            ]
        );
        $adminUser->syncRoles([$adminRole]);

        $ownerUser = User::updateOrCreate(
            ['email' => 'owner@schoolmapr.com'],
            [
                'name'     => 'Patna School Partner',
                'password' => Hash::make('owner123'),
                'phone'    => '+91 9876543211',
            ]
        );
        $ownerUser->syncRoles([$ownerRole]);

        $parentUser = User::updateOrCreate(
            ['email' => 'parent@schoolmapr.com'],
            [
                'name'     => 'Amit Sharma',
                'password' => Hash::make('parent123'),
                'phone'    => '+91 9876543212',
            ]
        );
        $parentUser->syncRoles([$parentRole]);

        $this->command->info("👤 Verified User Logins Created:");
        $this->command->info("   Admin:  admin@schoolmapr.com  / admin123");
        $this->command->info("   Owner:  owner@schoolmapr.com  / owner123");
        $this->command->info("   Parent: parent@schoolmapr.com / parent123");

        // ── Real Patna Schools Dataset (Across All Requested Localities) ──
        $schools = [
            // ── 1. Bailey Road / Danapur ──
            [
                'name'              => 'Delhi Public School Patna',
                'slug'              => 'delhi-public-school-patna',
                'city'              => 'Bailey Road',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Vill. Chandmari, Bailey Road, Danapur Cantt, Patna, Bihar 801502',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1998,
                'total_students'    => 4200,
                'principal_name'    => 'B. Vinod',
                'affiliation_no'    => '330053',
                'admission_status'  => 'open',
                'seats_available'   => 45,
                'admission_fee'     => 15000,
                'fee_min'           => 48000,
                'fee_max'           => 88000,
                'transport_fee'     => 18000,
                'latitude'          => 25.6208,
                'longitude'         => 85.0450,
                'image_url'         => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Smart Classrooms', 'Olympic Swimming Pool', 'Robotics Lab', 'AC Transport', 'Indoor Sports Complex', 'Science Labs'],
                'phone'             => '+91 612 2972797',
                'email'             => 'admissions@dpspatna.com',
                'website'           => 'https://dpspatna.com',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'Delhi Public School Patna is one of the premier institutions in Bihar, affiliated with CBSE. Known for stellar academic results, top IIT/NEET selections, world-class sports facilities, and holistic personality development.',
            ],

            // ── 2. Kurji / Digha ──
            [
                'name'              => 'St. Michael\'s High School',
                'slug'              => 'st-michaels-high-school-patna',
                'city'              => 'Kurji',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Digha Ghat, Kurji, Patna, Bihar 800011',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Boys',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1858,
                'total_students'    => 3500,
                'principal_name'    => 'Fr. Norbert Menezes SJ',
                'affiliation_no'    => '330004',
                'admission_status'  => 'open',
                'seats_available'   => 30,
                'admission_fee'     => 12000,
                'fee_min'           => 38000,
                'fee_max'           => 68000,
                'transport_fee'     => 14000,
                'latitude'          => 25.6425,
                'longitude'         => 85.1052,
                'image_url'         => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Spacious Football Ground', 'Basketball Courts', 'Advanced Physics & Chem Labs', 'Library with 25k books', 'Auditorium'],
                'phone'             => '+91 612 2262450',
                'email'             => 'info@stmichaelspatna.edu.in',
                'website'           => 'https://stmichaelspatna.edu.in',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'Founded in 1858 by Jesuit Fathers, St. Michael\'s High School is an iconic landmark of academic and athletic excellence in Patna, nurturing leaders across civil services, defense, and science.',
            ],

            // ── 3. Patliputra Colony ──
            [
                'name'              => 'Notre Dame Academy',
                'slug'              => 'notre-dame-academy-patna',
                'city'              => 'Patliputra',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Near P&T Colony, Patliputra, Patna, Bihar 800013',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Girls',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1960,
                'total_students'    => 3100,
                'principal_name'    => 'Sr. Mary Neha SND',
                'affiliation_no'    => '330018',
                'admission_status'  => 'open',
                'seats_available'   => 50,
                'admission_fee'     => 14000,
                'fee_min'           => 42000,
                'fee_max'           => 72000,
                'transport_fee'     => 15000,
                'latitude'          => 25.6310,
                'longitude'         => 85.1180,
                'image_url'         => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Lush Green Campus', 'Music & Dance Academies', 'Computer Center', 'STEM Robotics Lab', 'Multi-purpose Hall'],
                'phone'             => '+91 612 2277777',
                'email'             => 'contact@notredamepatna.in',
                'website'           => 'https://notredamepatna.in',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'Notre Dame Academy is the gold standard for girls education in Bihar. Run by the Sisters of Notre Dame, it empowers young women through high scholastic achievement and moral integrity.',
            ],

            // ── 4. Boring Road / Buddha Colony ──
            [
                'name'              => 'B.D. Public School',
                'slug'              => 'bd-public-school-patna',
                'city'              => 'Boring Road',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Buddha Colony, Near Boring Road Crossing, Patna, Bihar 800001',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1989,
                'total_students'    => 2800,
                'principal_name'    => 'Sheela Sinha',
                'affiliation_no'    => '330045',
                'admission_status'  => 'open',
                'seats_available'   => 40,
                'admission_fee'     => 10000,
                'fee_min'           => 34000,
                'fee_max'           => 62000,
                'transport_fee'     => 12000,
                'latitude'          => 25.6180,
                'longitude'         => 85.1260,
                'image_url'         => 'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Digital Classrooms', 'Air Conditioned Library', 'Biology & Maths Lab', 'CCTV Security', 'Dedicated Medical Room'],
                'phone'             => '+91 612 2521190',
                'email'             => 'admin@bdpublicschool.com',
                'website'           => 'https://bdpublicschool.com',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'B.D. Public School in Boring Road is celebrated for consistent top 10 rankings in CBSE board examinations and focused mentoring for engineering and medical entrance tests.',
            ],

            // ── 5. Kankarbagh ──
            [
                'name'              => 'St. Anne\'s High School',
                'slug'              => 'st-annes-high-school-kankarbagh',
                'city'              => 'Kankarbagh',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Housing Board Colony, Near Tempo Stand, Kankarbagh, Patna, Bihar 800020',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1982,
                'total_students'    => 2900,
                'principal_name'    => 'Sr. Elizabeth Mary',
                'affiliation_no'    => '330062',
                'admission_status'  => 'open',
                'seats_available'   => 35,
                'admission_fee'     => 11000,
                'fee_min'           => 36000,
                'fee_max'           => 64000,
                'transport_fee'     => 13000,
                'latitude'          => 25.5940,
                'longitude'         => 85.1550,
                'image_url'         => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Smart Board Classrooms', 'Taekwondo Training', 'Computer Laboratory', 'School Bus Fleet', 'Science Exhibition Hall'],
                'phone'             => '+91 612 2351234',
                'email'             => 'principal@stannespkb.edu.in',
                'website'           => 'https://stannespkb.edu.in',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'St. Anne\'s High School in Kankarbagh is one of the most trusted co-educational schools in South Patna, offering balanced academic grounding and extensive extracurricular opportunities.',
            ],

            // ── 6. Raja Bazar ──
            [
                'name'              => 'St. Dominic Savio\'s High School',
                'slug'              => 'st-dominic-savios-high-school-raja-bazar',
                'city'              => 'Raja Bazar',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Shiksha Kendra, Bailey Road, Raja Bazar, Patna, Bihar 800014',
                'board'             => 'ICSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1982,
                'total_students'    => 2400,
                'principal_name'    => 'Glenda Galstaun',
                'affiliation_no'    => 'BI012',
                'admission_status'  => 'open',
                'seats_available'   => 40,
                'admission_fee'     => 12500,
                'fee_min'           => 38000,
                'fee_max'           => 68000,
                'transport_fee'     => 14000,
                'latitude'          => 25.6120,
                'longitude'         => 85.0920,
                'image_url'         => 'https://images.unsplash.com/photo-1519452575417-564c1401ecc0?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['ICSE Curriculum Lab', 'Auditorium', 'Volleyball Court', 'Airy Classrooms', 'Bus GPS Tracking'],
                'phone'             => '+91 612 2287600',
                'email'             => 'info@stdominicsavios.com',
                'website'           => 'https://stdominicsavios.com',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'A leading ICSE school in Raja Bazar, Patna, St. Dominic Savio\'s is renowned for strong English communication training, debating championships, and high ISC board scores.',
            ],

            // ── 7. Ashiana Nagar (Aashiyana) ──
            [
                'name'              => 'Don Bosco Academy',
                'slug'              => 'don-bosco-academy-ashiana',
                'city'              => 'Ashiana Nagar',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Digha-Ashiyana Road, Ashiana Nagar, Patna, Bihar 800025',
                'board'             => 'ICSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1973,
                'total_students'    => 3200,
                'principal_name'    => 'Mary Alphonsa',
                'affiliation_no'    => 'BI002',
                'admission_status'  => 'open',
                'seats_available'   => 50,
                'admission_fee'     => 14000,
                'fee_min'           => 40000,
                'fee_max'           => 75000,
                'transport_fee'     => 15000,
                'latitude'          => 25.6260,
                'longitude'         => 85.0840,
                'image_url'         => 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Sports Complex', 'Cricket Turf', 'Language Lab', 'Modern Science Labs', 'Music Room'],
                'phone'             => '+91 612 2560389',
                'email'             => 'donboscopatna@gmail.com',
                'website'           => 'https://donboscopatna.com',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'Don Bosco Academy in Ashiana Nagar is one of Bihar\'s most prestigious ICSE/ISC schools, fostering intellectual brilliance, public speaking confidence, and sportsmanship.',
            ],

            // ── 8. Jakariyapur / Patna Bypass ──
            [
                'name'              => 'Trinity Global School',
                'slug'              => 'trinity-global-school-jakariyapur',
                'city'              => 'Jakariyapur',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'N.H. 30, Near Toll Plaza, Jakariyapur, Patna, Bihar 800030',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 2014,
                'total_students'    => 2100,
                'principal_name'    => 'Dr. Ananya Roy',
                'affiliation_no'    => '330812',
                'admission_status'  => 'open',
                'seats_available'   => 55,
                'admission_fee'     => 20000,
                'fee_min'           => 60000,
                'fee_max'           => 110000,
                'transport_fee'     => 22000,
                'latitude'          => 25.5780,
                'longitude'         => 85.2100,
                'image_url'         => 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Full Air-Conditioned Campus', 'Swimming Pool', 'Equestrian Club', 'Design & Innovation Lab', 'Boarding Available'],
                'phone'             => '+91 612 2999555',
                'email'             => 'admissions@trinityglobalschool.com',
                'website'           => 'https://trinityglobalschool.com',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'Trinity Global School on Patna Bypass/Jakariyapur is a futuristic international school featuring state-of-the-art sports academies, global curriculum pedagogy, and world-class AC facilities.',
            ],

            // ── 9. 70 Feet Road / Anisabad ──
            [
                'name'              => 'Radiant International School',
                'slug'              => 'radiant-international-school-70feet',
                'city'              => '70 Feet Road',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Khagaul - Anisabad 70 Feet Road, Patna, Bihar 801105',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 2001,
                'total_students'    => 3400,
                'principal_name'    => 'Col. K.S. Rathore',
                'affiliation_no'    => '330128',
                'admission_status'  => 'open',
                'seats_available'   => 40,
                'admission_fee'     => 14000,
                'fee_min'           => 45000,
                'fee_max'           => 78000,
                'transport_fee'     => 16000,
                'latitude'          => 25.5890,
                'longitude'         => 85.0810,
                'image_url'         => 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Horse Riding Arena', 'Shooting Range', 'Archery', 'Robotics & AI Lab', 'Modern Hostel for Boys & Girls'],
                'phone'             => '+91 612 2273030',
                'email'             => 'info@radiantpatna.edu.in',
                'website'           => 'https://radiantpatna.edu.in',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'Located near 70 Feet / Anisabad Road, Radiant International is spread across 8 acres with top tier military-grade sports infrastructure and exceptional academic coaching.',
            ],

            // ── 10. Saguna More / Danapur ──
            [
                'name'              => 'Litera Valley School',
                'slug'              => 'litera-valley-school-saguna-more',
                'city'              => 'Saguna More',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Near Saguna More, Danapur Main Road, Patna, Bihar 801503',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 2007,
                'total_students'    => 3300,
                'principal_name'    => 'Sharad Kumar',
                'affiliation_no'    => '330198',
                'admission_status'  => 'open',
                'seats_available'   => 60,
                'admission_fee'     => 16000,
                'fee_min'           => 46000,
                'fee_max'           => 82000,
                'transport_fee'     => 17000,
                'latitude'          => 25.6150,
                'longitude'         => 85.0380,
                'image_url'         => 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Zee Learn Smart Class', 'Lego Robotics Lab', 'Cricket Academy', 'Air Conditioned Buses', 'Art & Craft Studio'],
                'phone'             => '+91 612 2500055',
                'email'             => 'admissions@literavalley.edu.in',
                'website'           => 'https://literavalley.edu.in',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'Litera Valley School near Saguna More provides modern pedagogy, creative critical thinking curriculums, and strong STEM focus designed for 21st-century learners.',
            ],

            // ── 11. Gandhi Maidan / Ashok Rajpath ──
            [
                'name'              => 'St. Xavier\'s High School',
                'slug'              => 'st-xaviers-high-school-patna',
                'city'              => 'Gandhi Maidan',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Near Gandhi Maidan North, Ashok Rajpath, Patna, Bihar 800004',
                'board'             => 'ICSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1940,
                'total_students'    => 3800,
                'principal_name'    => 'Fr. K.P. Dominic SJ',
                'affiliation_no'    => 'BI001',
                'admission_status'  => 'open',
                'seats_available'   => 35,
                'admission_fee'     => 12000,
                'fee_min'           => 35000,
                'fee_max'           => 60000,
                'transport_fee'     => 13000,
                'latitude'          => 25.6185,
                'longitude'         => 85.1480,
                'image_url'         => 'https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Heritage Campus', 'Science Laboratories', 'Basketball Complex', 'Scout & Guides Unit', 'Extensive Library'],
                'phone'             => '+91 612 2677222',
                'email'             => 'admin@stxavierspatna.org',
                'website'           => 'https://stxavierspatna.org',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'St. Xavier\'s High School is one of the most historic and revered educational institutions in Bihar, producing distinguished alumni across national and international domains.',
            ],

            // ── 12. BSEB Colony / Punpun ──
            [
                'name'              => 'DAV Public School BSEB Colony',
                'slug'              => 'dav-public-school-bseb-patna',
                'city'              => 'BSEB Colony',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'BSEB Colony, New Punaichak, Patna, Bihar 800023',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1993,
                'total_students'    => 4600,
                'principal_name'    => 'V.S. Ojha',
                'affiliation_no'    => '330039',
                'admission_status'  => 'open',
                'seats_available'   => 50,
                'admission_fee'     => 9000,
                'fee_min'           => 30000,
                'fee_max'           => 55000,
                'transport_fee'     => 12000,
                'latitude'          => 25.6090,
                'longitude'         => 85.1140,
                'image_url'         => 'https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Vedic Cultural Center', 'High Speed Computer Labs', 'Maths Olympiad Cell', 'Gymnasium', 'Auditorium'],
                'phone'             => '+91 612 2283459',
                'email'             => 'davbsebpatna@gmail.com',
                'website'           => 'https://davbsebpatna.org',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'DAV BSEB is famous across Eastern India for yielding the highest number of IIT-JEE, NEET, and NTSE rankers with an affordable and value-based education model.',
            ],

            // ── 13. Gola Road / Danapur ──
            [
                'name'              => 'St. Karen\'s High School',
                'slug'              => 'st-karens-high-school-gola-road',
                'city'              => 'Gola Road',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Gola Road, Bailey Road, Danapur, Patna, Bihar 801503',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 1965,
                'total_students'    => 3700,
                'principal_name'    => 'Sharon Galstaun',
                'affiliation_no'    => '330051',
                'admission_status'  => 'open',
                'seats_available'   => 45,
                'admission_fee'     => 13000,
                'fee_min'           => 39000,
                'fee_max'           => 69000,
                'transport_fee'     => 14000,
                'latitude'          => 25.6170,
                'longitude'         => 85.0560,
                'image_url'         => 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Extensive Sports Ground', 'Air-Conditioned Labs', 'Smart Classrooms', 'Safe Transport Fleet', 'Art Center'],
                'phone'             => '+91 612 2789123',
                'email'             => 'info@stkarens.com',
                'website'           => 'https://stkarens.com',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => true,
                'description'       => 'St. Karen\'s High School on Gola Road is synonymous with discipline, outstanding CBSE academic merit, and moral values.',
            ],

            // ── 14. Kumhrar / Bhagwat Nagar ──
            [
                'name'              => 'Pushpalata Patil International School',
                'slug'              => 'pushpalata-patil-international-school-kumhrar',
                'city'              => 'Kumhrar',
                'district'          => 'Patna',
                'state'             => 'Bihar',
                'address'           => 'Near Kumhrar Archaeological Park, Bhagwat Nagar, Patna, Bihar 800026',
                'board'             => 'CBSE',
                'medium'            => 'English',
                'school_type'       => 'Co-Ed',
                'class_from'        => 1,
                'class_to'          => 12,
                'established_year'  => 2005,
                'total_students'    => 2600,
                'principal_name'    => 'Dr. R.K. Pandey',
                'affiliation_no'    => '330214',
                'admission_status'  => 'open',
                'seats_available'   => 40,
                'admission_fee'     => 12000,
                'fee_min'           => 38000,
                'fee_max'           => 68000,
                'transport_fee'     => 13000,
                'latitude'          => 25.5990,
                'longitude'         => 85.1850,
                'image_url'         => 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1200&q=80',
                'facilities'        => ['Modern Science Block', 'Skating Rink', 'Computer Center', 'Music Studio', 'CCTV Campus'],
                'phone'             => '+91 612 2368899',
                'email'             => 'info@ppispatna.edu.in',
                'website'           => 'https://ppispatna.edu.in',
                'status'            => 'approved',
                'is_active'         => true,
                'is_verified'       => true,
                'is_featured'       => false,
                'description'       => 'Pushpalata Patil International School in Kumhrar blends academic depth with sports and culture, preparing students for competitive examinations and character building.',
            ],
        ];

        foreach ($schools as $data) {
            School::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }

        $this->command->info("✅ " . count($schools) . " Patna schools successfully seeded for SchoolMapr!");
    }
}
